### ISSUE TITLE
The text inside P tags is being selected on mobile devices

### ISSUE THREAD

**Issue by Neopentene** [gitryder/synement#10]
**Description**
The text in p tags inside the div tags with class names as assignment , quiz, experiment and other is being selected on click from mobile devices. 

**To Reproduce**
1. Go to syne.danyl.xyz from a mobile device
2. Click on any of the p tags with text: 'A', 'Q', 'O', 'E' 
3. See the text being selected

**Expected behavior**
The text inside the p tags was not supposed to be selected on click 

**Screenshots**
First Screenshot
![Screenshot_20210918-172943_Chrome](https://user-images.githubusercontent.com/82939252/133888120-1c92302e-ee50-4084-bef8-af3fdbd99edf.jpg)

Second Screenshot
![Screenshot_20210918-173016_Chrome](https://user-images.githubusercontent.com/82939252/133888122-9b3ed805-0f6f-4023-8016-354b545cf93c.jpg)

**Additional context**
This bug is really annoying as I access this site from mobile and sometimes click on the p tags.

**Comment by gitryder** [comment]
Hi :wave:  thanks for the issue. 

Since the PR submitted wasn't a permanent fix, [a fix](https://github.com/gitryder/synement/commit/ec97ed) has now been issued.
 
Please run the latest codebase and verify if the issue still exists.
