### ISSUE TITLE
Background isn't full-screen on mobile browsers' "Desktop Mode"

### ISSUE THREAD

**Issue by grewscant** [gitryder/synement#5]
**Describe the bug**
- The Background isn't full-screen on mobile browsers' "Desktop Mode"
- The background is only as big as the length of the last work card.
- After which a white background is seen.

**To Reproduce**
1. Go to https://grewscant.github.io/synement/
2. Click your browser's "Desktop site" option.
3. Scroll down to the end.
4. You will see a white background instead of the original gradient background

**Expected behavior**
The default gradient background should always fill the screen regardless of the screen size.

**Desktop (please complete the following information):**
 - All OSs
 - Any Browser
 - Synement v0.3.2

**Comment by ganm0r** [comment]
Good afternoon. Working on the bug, too. How to test though? I tried using the link provided by React build for the network on my mobile. But it's not opening.

**Comment by grewscant** [comment]
On linux, do `ifconfig` and then use your laptop's local IP on your phone.
