### ISSUE TITLE
Additional details for each work card

### ISSUE THREAD

**Issue by grewscant** [gitryder/synement#8]
**Is your feature request related to a problem? Please describe.**
User must login into the ERP to check what the exact details of the Assignment / Experiment are.

**Describe the solution you'd like**
- Some way to see more details on the card but while still not compromising on design.
- Thinking of something like a flip card or something. Not sure.

**Potential Problems:**
- Synement API v0.31 doesn't return experiment details anymore.
- Also, the details for some experiments is so large that it's not even a good idea to display them on the front end.

**Thinking out loud:**
- What if we could just take them to the ERPs page?
    - That'd be great, but wait, they'll have to login everytime. We don't want that.
- How 'bout a modal upon click?
    - Nice, but that will bloat the UI, won't it?

**Describe alternatives you've considered**
None. The only solution is to login to ERP.

**Comment by ganm0r** [comment]
Yes. Thought of redirecting to the ERP on card click. But the user will have to login every time. Very redundant.

**What can be done is this:**

- A pop-up component for each card on card click. This allows really large details to be conveyed, without making the UI too verbose.
- Also, an additional detail on the current card design, should be the number of the assignment/experiment. This could be a completely different issue, because the current scheme for differentiating between the task type, would have to be altered.

**Comment by grewscant** [comment]
> A pop-up component for each card on card click. This allows really large details to be conveyed, without making the UI too verbose

Yes, that's called a modal (or a modal dialog). Makes sense but would slightly bloat the UI. But even if we build it, [the API](https://synement.herokuapp.com/te/today) doesn't return `details` anymore. And adding that would be a whole different ballgame altogether.

> This could be a completely different issue

Yes, you're right. That should be a seperate issue with a proper explanation of why that is important.

**Comment by shubh2305** [comment]
**What if we add a expand/collapse to the cards 

> ?**When the card is expanded we show the details 
> ?**And when it is collapsed it will only display the title and date

**Comment by shubh2305** [comment]
**What if we add an expand/collapse to the cards ?**

- When the card is expanded it will display the details
- When it s collapsed it will display the date and the title like now

**Comment by grewscant** [comment]
Sure. But the design will have to be decided first. Also the API needs to be updated. If you can create the component with test data separately, that would be great.

**Comment by shubh2305** [comment]
Okay
