### ISSUE TITLE
Get assignment id and details of the experiment/assignment

### ISSUE THREAD

**Issue by shubh2305** [gitryder/synement#9]
Want to add a feature of onClick on the experiment divs which will redirect the user to the submission of the respective assignment. 
And also show the details of the respective assignment using expand/collapse

https://user-images.githubusercontent.com/65953776/133230881-29c11235-76ec-432a-a297-31a9a84b25d2.mp4

The above video suggests the onclick feature but the url is currently hardcoded

**Comment by gitryder** [comment]
First of all, this is brilliant! :confetti_ball: 

## 1

> but the url is currently hardcoded

What do you need from the API? The `Assignment_ID`, I'm guessing, right? Let's try that out.

## 2

- I cannot see the `type` on the cards. 
- I think you're on an older codebase. 
- Can you please update to the latest codebase first.

**Comment by gitryder** [comment]
## To update: (Assuming your working tree is clean)
1. 
```
git remote add upstream https://github.com/gitryder/synement.git
```

2. 
```
git pull upstream master
```

**Comment by shubh2305** [comment]
> ## 2
> * I cannot see the `type` on the cards.
> * I think you're on an older codebase.
> * Can you please update to the latest codebase first.

Yeah I havent pulled the latest code yet. I will do that

**Comment by shubh2305** [comment]
> What do you need from the API? The `Assignment_ID`, I'm guessing, right? Let's try that out.

Yes I need the assignment id

**Comment by grewscant** [comment]
Hi @shubh2305, any progress?

**Comment by grewscant** [comment]
The API has been updated. Such is the output now:
```json
[
  {
    "id": 229,
    "subject": "Software Engineering Lab",
    "type": "Assignment",
    "date_due": "20-Sep-2021",
    "link": "https://xavier.qualcampus.com/Dashboard_Assignment_Student/SubmitAssignment?Assignment_ID=229"
  },
  {
    "id": 93,
    "subject": "CN-Quiz-Module-2",
    "type": "Quiz",
    "date_due": "20-Sep-2021",
    "link": "https://xavier.qualcampus.com/Quiz_Attempt/Index?Quiz_ID=93"
  }
]
```

**Comment by grewscant** [comment]
Please let me know if you want this to be assigned to you. 
Since you have not replied, this will be automatically assigned to me by tonight.
